#!/usr/bin/env python3
"""
Convert SPIR-V shaders to C++ embedded byte arrays for LSFG-VK integration.

This generates a header file that can be included in LSFG-VK's shader pool,
replacing the filesystem-based shader loading with embedded binaries.
"""

import os
import glob
import re

def sanitize_filename(filename):
    """Convert shader_000.spv to SHADER_000"""
    name = os.path.splitext(filename)[0]  # Remove .spv
    return name.upper()

def generate_shader_header(output_path="shaders_embedded.hpp"):
    """Generate C++ header with embedded shader binaries."""
    
    raw_dir = "raw"
    spv_files = sorted(glob.glob(os.path.join(raw_dir, "shader_*.spv")))
    
    # Filter to only valid shaders (under 64KB means not truncated)
    valid_shaders = []
    for spv_path in spv_files:
        size = os.path.getsize(spv_path)
        # Skip likely truncated shaders
        if size >= 65536:
            print(f"Skipping {os.path.basename(spv_path)} ({size} bytes, likely truncated)")
            continue
        valid_shaders.append(spv_path)
    
    print(f"\nEmbedding {len(valid_shaders)} valid shaders...")
    
    lines = []
    lines.append("// Auto-generated by embed_shaders.py")
    lines.append("// Embedded SPIR-V shaders from GameScopeVK")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("#include <vector>")
    lines.append("#include <unordered_map>")
    lines.append("#include <string>")
    lines.append("")
    lines.append("namespace GameScopeVK {")
    lines.append("namespace Shaders {")
    lines.append("")
    
    # Generate byte arrays for each shader
    for spv_path in valid_shaders:
        filename = os.path.basename(spv_path)
        var_name = sanitize_filename(filename)
        
        with open(spv_path, 'rb') as f:
            data = f.read()
        
        # Format as C++ byte array
        lines.append(f"// {filename} - {len(data)} bytes")
        lines.append(f"constexpr uint8_t {var_name}[] = {{")
        
        # Write bytes in rows of 12 for readability
        row_size = 12
        for i in range(0, len(data), row_size):
            row = data[i:i+row_size]
            hex_bytes = ", ".join(f"0x{b:02x}" for b in row)
            if i + row_size < len(data):
                lines.append(f"    {hex_bytes},")
            else:
                lines.append(f"    {hex_bytes}")
        
        lines.append("};")
        lines.append("")
    
    # Generate shader registry
    lines.append("// Shader registry for lookup by name")
    lines.append("inline const std::unordered_map<std::string, std::pair<const uint8_t*, size_t>> SHADER_REGISTRY = {")
    
    for spv_path in valid_shaders:
        filename = os.path.basename(spv_path)
        var_name = sanitize_filename(filename)
        size = os.path.getsize(spv_path)
        # Skip truncated for registry
        if size >= 65500:
            continue
        lines.append(f'    {{"{filename}", {{{var_name}, sizeof({var_name})}}}},')
    
    lines.append("};")
    lines.append("")
    
    # Helper function
    lines.append("// Get shader data by name")
    lines.append("inline std::vector<uint8_t> GetShader(const std::string& name) {")
    lines.append("    auto it = SHADER_REGISTRY.find(name);")
    lines.append("    if (it != SHADER_REGISTRY.end()) {")
    lines.append("        return std::vector<uint8_t>(it->second.first, it->second.first + it->second.second);")
    lines.append("    }")
    lines.append("    return {};  // Empty if not found")
    lines.append("}")
    lines.append("")
    
    # Helper to list all shaders
    lines.append("// Get list of all available shader names")
    lines.append("inline std::vector<std::string> GetShaderNames() {")
    lines.append("    std::vector<std::string> names;")
    lines.append("    for (const auto& [name, _] : SHADER_REGISTRY) {")
    lines.append("        names.push_back(name);")
    lines.append("    }")
    lines.append("    return names;")
    lines.append("}")
    
    lines.append("")
    lines.append("} // namespace Shaders")
    lines.append("} // namespace GameScopeVK")
    lines.append("")
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"\nGenerated {output_path}")
    print(f"  Total shaders: {len(valid_shaders)}")
    total_size = sum(os.path.getsize(p) for p in valid_shaders)
    print(f"  Total size: {total_size:,} bytes ({total_size/1024:.1f} KB)")
    
    return valid_shaders

if __name__ == "__main__":
    shaders = generate_shader_header()
    
    # Also generate a summary
    print("\nShader embedding complete. Next steps:")
    print("  1. Copy shaders_embedded.hpp to lsfg-vk-upstream/framegen/include/")
    print("  2. Modify LSFG-VK's shader pool to use embedded shaders")
    print("  3. Build and test with modified liblsfg-vk.so")
